# Base configuration for every Zeliblue image

modules:

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: files
    files:
      - shared/usr: /usr
      - shared/etc: /etc

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
      google-fonts:
        - Inter

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
    install:
      - fish
      - gcc
      - glow
      - gum
      - system76-scheduler
    remove:
      - firefox
      - firefox-langpacks

  - type: containerfile
    snippets:
      - RUN rm /etc/yum.repos.d/charm.repo

  - type: default-flatpaks
    system:
      repo-name: flathub-system
      repo-title: "Flathub (system-wide)"
    user:
      repo-name: flathub-user

  - type: systemd
    system:
      enabled:
        - com.system76.Scheduler.service

  - type: brew

  - type: yafti

  - type: signing

  - type: script
    scripts:
      - image-info.sh
