modules:

  - type: files
    files:
      - gnome/usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    install:
      - gnome-console
      - gnome-shell-extension-hotedge
    remove:
      - gnome-classic-session
      - gnome-classic-session-xsession
      - gnome-software-rpm-ostree
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-tweaks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - io.github.celluloid_player.Celluloid
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Contacts
        - com.vixalien.decibels
        - org.gnome.baobab
        - org.gnome.SimpleScan
        - org.gnome.Evince
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.Epiphany
        - com.github.tchx84.Flatseal
        - org.gnome.World.PikaBackup
      remove:
        - org.gnome.NautilusPreviewer

  - type: gschema-overrides
    include:
      - zz0-zeliblue.gschema.override
