modules:

  - type: files
    files:
      - pantheon/etc: /etc

  - type: rpm-ostree
    install:
      - dbus-x11
      - gnome-session
      - gvfs
      - gvfs-afc
      - gvfs-afp
      - gvfs-fuse
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - xdg-user-dirs-gtk
      - xorg-x11-drv-amdgpu
      - xorg-x11-drv-ati
      - xorg-x11-drv-evdev
      - xorg-x11-drv-fbdev
      - xorg-x11-drv-libinput
      - xorg-x11-drv-nouveau
      - xorg-x11-drv-qxl
      - xorg-x11-drv-wacom
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-xinit
      - xorg-x11-drv-intel
      - xorg-x11-drv-openchrome
      - xorg-x11-drv-vesa
      - xorg-x11-drv-vmware

  - type: rpm-ostree
    install:
      - appcenter
      - elementary-code
      - elementary-files
      - elementary-greeter
      - elementary-icon-theme
      - elementary-notifications
      - elementary-onboarding
      - elementary-photos
      - elementary-print
      - elementary-settings-daemon
      - elementary-shortcut-overlay
      - elementary-sideload
      - elementary-sound-theme
      - elementary-terminal
      - elementary-theme
      - elementary-wallpapers
      - gala
      - light-locker
      - granite-7
      - pantheon-agent-geoclue2
      - pantheon-agent-polkit
      - pantheon-session-settings
      - switchboard-plug-a11y
      - switchboard-plug-about
      - switchboard-plug-applications
      - switchboard-plug-bluetooth
      - switchboard-plug-datetime
      - switchboard-plug-display
      - switchboard-plug-keyboard
      - switchboard-plug-locale
      - switchboard-plug-mouse-touchpad
      - switchboard-plug-networking
      - switchboard-plug-notifications
      - switchboard-plug-onlineaccounts
      - switchboard-plug-pantheon-shell
      - switchboard-plug-parental-controls
      - switchboard-plug-power
      - switchboard-plug-printers
      - switchboard-plug-security-privacy
      - switchboard-plug-sharing
      - switchboard-plug-sound
      - switchboard-plug-useraccounts
      - switchboard-plug-wacom
      - switchboard-plug-wallet
      - switchboard
      - touchegg
      - wingpanel-applications-menu
      - wingpanel-indicator-bluetooth
      - wingpanel-indicator-datetime
      - wingpanel-indicator-keyboard
      - wingpanel-indicator-network
      - wingpanel-indicator-nightlight
      - wingpanel-indicator-notifications
      - wingpanel-indicator-power
      - wingpanel-indicator-session
      - wingpanel-indicator-sound
      - wingpanel
      - xdg-desktop-portal-pantheon

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://flatpak.elementary.io/repo.flatpakrepo
      repo-name: appcenter-system
      repo-title: "AppCenter (system-wide)"
      install:
        - io.elementary.calculator//stable
        - io.elementary.calendar//stable
        - io.elementary.camera//stable
        - io.elementary.capnet-assist//stable
        - io.elementary.mail//daily
        - io.elementary.music//stable
        - io.elementary.screenshot//stable
        - io.elementary.tasks//stable
        - io.elementary.videos//stable
        - org.gnome.Epiphany//stable
        - org.gnome.Evince//stable
        - org.gnome.FileRoller/stable
    user:
      repo-url: https://flatpak.elementary.io/repo.flatpakrepo
      repo-name: appcenter-user
      repo-title: "AppCenter"