css: |
  .curated-section {
    margin: 12px;
  }
  .curated-section banner-text {
    padding: 24px;
    color: var(--accent-color);
  }
  .curated-section title {
    font-size: 2em;
  }
sections:
  - title: "Web Browsers"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - org.mozilla.firefox
      - com.google.Chrome
      - com.vivaldi.Vivaldi
      - org.chromium.Chromium
      - com.microsoft.Edge
    classes:
      - curated-section
  - title: "Media"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - de.haeckerfelix.Shortwave
      - io.bassi.Amberol
      - com.github.neithern.g4music
      - com.github.wwmm.easyeffects
      - com.rafaelmardojai.Blanket
      - org.gnome.SoundRecorder
      - org.audacityteam.Audacity
      - org.ardour.Ardour
      - com.obsproject.Studio
      - org.kde.kdenlive
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
    classes:
      - curated-section
  - title: "Office & Productivity"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - org.gnome.gitlab.somas.Apostrophe
      - io.github.alainm23.planify
      - com.vixalien.sticky
      - io.github.mrvladus.List
      - re.sonny.Eloquent
      - org.onlyoffice.desktopeditors
      - org.libreoffice.LibreOffice
      - app.drey.Typewriter
      - com.github.PintaProject.Pinta
      - org.kde.krita
      - org.inkscape.Inkscape
      - org.blender.Blender
      - io.github.nokse22.Exhibit
      - org.gnome.Fractal
    classes:
      - curated-section
  - title: "Games"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - com.discordapp.Discord
      - com.valvesoftware.Steam
      - io.itch.itch
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - com.vysp3r.ProtonPlus
      - com.github.Matoking.protontricks
      - com.feaneron.Boatswain
      - com.valvesoftware.SteamLink
      - org.gnome.Crosswords
      - org.gnome.Aisleriot
      - org.gnome.Mahjongg
      - org.gnome.Sudoku
    classes:
      - curated-section
  - title: "Utilities"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - org.gnome.gitlab.cheywood.Buffer
      - io.github.kelvinnovais.Kasasa
      - app.drey.Warp
      - io.github.nozwock.Packet
      - io.gitlab.theevilskeleton.Upscaler
      - org.gnome.gitlab.cheywood.Pulp
      - io.gitlab.adhami3310.Impression
      - com.belmoussaoui.Decoder
      - com.belmoussaoui.Authenticator
      - org.gnome.World.Secrets
      - com.bitwarden.desktop
      - io.gitlab.adhami3310.Converter
      - com.jeffser.Pigment
      - com.github.finefindus.eyedropper
      - be.alexandervanhee.gradia
      - page.codeberg.libre_menu_editor.LibreMenuEditor
    classes:
      - curated-section
  - title: "Developers"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - io.podman_desktop.PodmanDesktop
      - com.ranfdev.DistroShelf
      - org.gnome.Boxes
      - org.gnome.Builder
      - dev.zed.Zed
      - re.sonny.Commit
      - me.iepure.devtoolbox
      - de.leopoldluley.Clapgrep
      - app.drey.KeyRack
      - io.github.lo2dev.Echo
      - org.gnome.design.IconLibrary
      - io.github.ronniedroid.concessio
      - dev.geopjr.Calligraphy
      - io.github.nokse22.asciidraw
      - dev.geopjr.Collision
      - io.github.tobagin.digger
      - io.github.plrigaux.sysd-manager
    classes:
      - curated-section
  - title: "Knowledge & Education"
    banner-fit: cover
    banner-text-halign: start
    banner-text-valign: center
    banner-height: 100
    appids:
      - org.endlessos.Key
      - io.github.david_swift.Flashcards
      - dev.bragefuglseth.Keypunch
      - org.tuxpaint.Tuxpaint
      - im.bernard.Memorado
      - io.github.nokse22.trivia-quiz
      - io.github.josephmawa.Egghead
      - io.github.r_sergii.multiElement
      - org.turbowarp.TurboWarp
      - com.github.hugolabe.Wike
      - app.drey.Dialect
      - com.github.johnfactotum.QuickLookup
    classes:
      - curated-section
