# run with --cap-add sys_admin --security-opt label=disable --squash

FROM ghcr.io/zelikos/zeliblue:stable
COPY ./iso_files /src
RUN --mount=type=cache,target=/var/tmp/libdnf5,id=libdnf5 \
    /src/build.sh
RUN rm -fr /src
