sections:
  - title: "Recommended"
    # subtitle: "The first section"
    # description: "These are some of my favorite apps!"
    rows: 3
    # use the file:// prefix for a local file
    banner: https://pixls.us/articles/processing-a-nightscape-in-siril/resultat_03_final.jpg
    # can be "fill", "contain", "cover", or "scale-down"
    banner-fit: cover
    appids:
      - org.mozilla.firefox
      - org.gimp.GIMP
      - org.gnome.Builder
      - org.inkscape.Inkscape
      - org.kde.krita
      - org.libreoffice.LibreOffice
      - io.github.mrvladus.List
      - com.vixalien.sticky
      - com.obsproject.Studio
      - org.kde.kdenlive
