# Base configuration for every Zeliblue image

modules:

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: files
    files:
      - shared: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
      google-fonts:
        - Inter

  - type: rpm-ostree
    install:
      - fish
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    system:
      repo-name: flathub-system
      repo-title: "Flathub (system-wide)"
    user:
      repo-name: flathub-user

  - type: yafti

  - type: signing

  - type: script
    scripts:
      - image-info.sh
