modules:

- type: rpm-ostree
  install:
  - gnome-console
  remove:
  - gnome-classic-session
  - gnome-terminal
  - gnome-terminal-nautilus

- type: flatpaks
  system:
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub-system
    repo-title: "Flathub (system-wide)"
    install:
    - org.gnome.Calculator
    - org.gnome.Calendar
    - io.github.celluloid_player.Celluloid
    - org.gnome.Characters
    - org.gnome.clocks
    - org.gnome.Contacts
    - org.gnome.baobab
    - org.gnome.SimpleScan
    - org.gnome.Evince
    - org.gnome.font-viewer
    - org.gnome.Logs
    - org.gnome.Loupe
    - org.gnome.Maps
    - org.gnome.NautilusPreviewer
    - org.gnome.TextEditor
    - org.gnome.Weather
    - org.gnome.Epiphany
    - com.github.tchx84.Flatseal
    - org.gnome.World.PikaBackup
  user:
    repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
    repo-name: flathub-user
