# image will be published to ghcr.io/<user>/<name>
name: zeliblue-deck
# description will be included in the image's metadata
description: A zeliblue-based SteamOS experience

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common-config.yml
  - from-file: gnome-config.yml

  - type: files
    files:
      - deck: /usr

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    install:
      - gamescope
      - gamescope-session-plus
      - gamescope-session-steam
      - libei
      - libei.i686
      - mangohud
      - sddm
      - sddm-sugar-steamOS
      # - steam
    remove:
      - mesa-va-drivers-freeworld

  - type: systemd
    system:
      enabled:
        - zelideck-autologin.service
        - sddm.service
      disabled:
        - gdm.service
    user:
      enabled:
        - zelideck-gamescope-setup.service

  - type: script
    scripts:
      - steam-install.sh
      - steamos-setup.sh
