# image will be published to ghcr.io/<user>/<name>
name: zeliblue
# description will be included in the image's metadata
description: Akzel's custom uBlue image, based on https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common-config.yml
  - from-file: gnome-config.yml
