# image will be published to ghcr.io/<user>/<name>
name: zeliblue-gts
# description will be included in the image's metadata
description: Zeliblue GTS (Grand Touring Series), for those needing extra stability

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: gts

# list of modules, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common-config.yml
  - from-file: gnome-config.yml
