title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Zeliblue"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
  sign-image:
    source: yafti.screen.package
    values:
      title: Signing Zeliblue
      condition:
        run: grep -qvz "signed" <<< $(rpm-ostree status)
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Sign Zeliblue:
          description: |
            This will sign your current install of Zeliblue. Mandatory for offline installs. This will take some time.
          default: true
          packages:
          - Sign Zeliblue: just --unstable sign-image
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Apps":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://universal-blue.org
      description: |
        Thanks for trying Zeliblue, we hope you enjoy it!
