title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Zeliblue (Alpha)"
      icon: "/path/to/icon"
      description: |
        Configure your system to get started.
  sign-image:
    source: yafti.screen.package
    values:
      title: Signing Zeliblue
      condition:
        run: grep -qvz "signed" <<< $(rpm-ostree status)
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Sign Bazzite:
          description: |
            This will sign your current install of Zeliblue. Mandatory for offline installs. This will take some time.
          default: true
          packages:
          - Sign Bazzite: just --unstable sign-image
  applications:
    source: yafti.screen.package
    values:
      title: App Installation
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      groups:
        Utilities:
          description: Apps for more advanced use cases.
          default: false
          packages:
            - Black Box (Terminal):
                package: com.raggesilver.BlackBox
                system: false
                user: true
            - Boxes:
                package: org.gnome.Boxes
                system: false
                user: true
            - Extensions Manager:
                package: com.mattjakeman.ExtensionManager
                system: false
                user: true
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Apps":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying Zeliblue, we hope you enjoy it!
