[misc]
only = ["brew_cask", "brew_formula", "system"]
ignore_failures = ["brew_cask", "brew_formula"]
skip_notify = true
assume_yes = true
no_retry = true
no_self_update = true

[linux]
rpm_ostree = true
