modules:

  - type: files
    files:
      - kinoite/usr: /usr

  - type: rpm-ostree
    # install:
    #  - ksystemlog
    remove:
      - ark
      - ark-libs
      - filelight
      - kate
      - kate-plugins
      - kfind
      - kwrite

  - type: default-flatpaks
    system:
      install:
        - org.kde.ark
        - org.kde.filelight
        - org.kde.gwenview
        - org.kde.haruna
        - org.kde.kalk
        - org.kde.kclock
        - org.kde.kfind
        - org.kde.kweather
        - org.kde.kwrite
        - org.kde.okular
        - org.mozilla.firefox
        - com.borgbase.Vorta
        - com.github.tchx84.Flatseal
        - org.gnome.Logs
