[misc]
only = ["brew_cask", "brew_formula", "distrobox", "system", "toolbx"]
ignore_failures = ["brew_cask", "brew_formula", "distrobox", "toolbx"]
skip_notify = true
assume_yes = true
no_retry = true
no_self_update = true

[distrobox]
use_root = false

[linux]
rpm_ostree = true
