# Install bazzite kernel
COPY --from=ghcr.io/ublue-os/akmods:bazzite-42 /kernel-rpms /tmp/bazzite-kernel-rpms
RUN --mount=type=cache,dst=/var/cache/libdnf5 \
    --mount=type=cache,dst=/var/cache/rpm-ostree \
    echo "Installing Bazzite kernel" && \

    dnf5 -y remove --no-autoremove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra && \

    dnf5 -y install \
    /tmp/bazzite-kernel-rpms/kernel-[0-9]*.rpm \
    /tmp/bazzite-kernel-rpms/kernel-core-*.rpm \
    /tmp/bazzite-kernel-rpms/kernel-modules-*.rpm

# Install akmods
# COPY --from=ghcr.io/ublue-os/akmods-extra:bazzite-41 /rpms /tmp/akmods-rpms
# RUN --mount=type=cache,dst=/var/cache/rpm-ostree \
#     echo "Installing akmods" && \
#     rpm-ostree install \
#     /tmp/akmods-rpms/kmods/*ryzen-smu*.rpm \
#     /tmp/akmods-rpms/kmods/*zenergy*.rpm
