title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Zeliblue"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
  dev-options:
    source: yafti.screen.package
    values:
      title: Developer Options
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Setup Homebrew:
          description: |
            This will setup Homebrew on your system. Homebrew allows easy installation of CLI utilities from your host terminal. See https://brew.sh/ for more information.
          default: false
          packages:
          - Install Homebrew: just --unstable brew
          - Enable Homebrew in shells: just --unstable brew-shell
          - Install some CLI utilities: just --unstable brew-utilities
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Apps":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://github.com/zelikos/zeliblue
        - "Universal Blue":
            run: /usr/bin/xdg-open https://universal-blue.org
      description: |
        Thanks for trying Zeliblue, we hope you enjoy it!
