title: Welcome to Zeliblue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to Zeliblue"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
  suggested-apps:
    source: yafti.screen.package
    values:
      title: Suggested Apps
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Web Browsers:
          description: Additional web browsers
          default: false
          packages:
            - Mozilla Firefox: org.mozilla.firefox
            - Google Chrome: com.google.Chrome
        Chat:
          description: Talk with the world
          default: false
          packages:
            - Discord: com.discordapp.Discord
            - Element: im.riot.Riot
        Gaming:
          description: Play games
          default: false
          packages:
            - Steam: com.valvesoftware.Steam
            - itch: io.itch.itch
            - Lutris: net.lutris.Lutris
        Graphics:
          description: Visual design and photography
          default: false
          packages:
            - Darktable: org.darktable.Darktable
            - Krita: org.kde.krita
            - GIMP: org.gimp.GIMP
            - Inkscape: org.inkscape.Inkscape
        Productivity:
          description: Keep organized, get work done
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - Errands: io.github.mrvladus.List
            - Sticky Notes: com.vixalien.sticky
        Streaming:
          description: Broadcast to the internet
          default: false
          packages:
            - OBS Studio: com.obsproject.Studio
            - OBS GStreamer Plugin: com.obsproject.Studio.Plugin.Gstreamer
            - Boatswain (Streamdeck app): com.feaneron.Boatswain
  dev-options:
    source: yafti.screen.package
    values:
      title: Developer Options
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:
        Setup Homebrew:
          description: |
            This will setup Homebrew on your system. Homebrew allows easy installation of CLI utilities from your host terminal. See https://brew.sh/ for more information.
          default: false
          packages:
            - Install Homebrew: just --unstable brew
            - Enable Homebrew in shells: just --unstable brew-shell
            - Install some CLI utilities: just --unstable brew-utilities
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Apps":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://github.com/zelikos/zeliblue
        - "Universal Blue":
            run: /usr/bin/xdg-open https://universal-blue.org
      description: |
        Thanks for trying Zeliblue, we hope you enjoy it!
