default:
  @just --list

bios:
  systemctl reboot --firmware-setup

changelogs:
  rpm-ostree db diff --changelogs

distrobox-boxkit:
  #!/bin/bash
  echo 'Creating Boxkit distrobox ...'
  distrobox create --image ghcr.io/ublue-os/boxkit -n boxkit -Y

distrobox-debian:
  #!/bin/bash
  echo 'Creating Debian distrobox ...'
  distrobox create --image quay.io/toolbx-images/debian-toolbox:unstable -n debian -Y

distrobox-opensuse:
  #!/bin/bash
  echo 'Creating openSUSE distrobox ...'
  distrobox create --image quay.io/toolbx-images/opensuse-toolbox:tumbleweed -n opensuse -Y

distrobox-ubuntu:
  #!/bin/bash
  echo 'Creating Ubuntu distrobox ...'
  distrobox create --image quay.io/toolbx-images/ubuntu-toolbox:22.04 -n ubuntu -Y

setup-flatpaks:
  #!/usr/bin/env bash
  echo 'Installing flatpaks from the ublue recipe ...'
  flatpaks=$(yq '.flatpaks[]' < /usr/share/ublue-os/recipe.yml)
  for pkg in $flatpaks; do \
      echo "Installing: ${pkg}" && \
      flatpak install --user --noninteractive flathub $pkg; \
  done

setup-gaming:
  #!/bin/bash
  echo 'Setting up gaming experience ... lock and load.'
  flatpak install -y --user \
  com.discordapp.Discord \
  org.freedesktop.Platform.GStreamer.gstreamer-vaapi//22.08 \
  org.freedesktop.Platform.VulkanLayer.MangoHud//22.08 \
  org.freedesktop.Platform.VulkanLayer.OBSVkCapture//22.08 \
  org.freedesktop.Platform.VulkanLayer.vkBasalt//22.08 \
  com.obsproject.Studio \
  com.obsproject.Studio.Plugin.OBSVkCapture \
  com.obsproject.Studio.Plugin.Gstreamer \
  com.valvesoftware.Steam \
  com.valvesoftware.Steam.Utility.gamescope
  flatpak override --user --env=MANGOHUD=1 com.valvesoftware.Steam
  flatpak override --user --env=OBS_VKCAPTURE=1 com.valvesoftware.Steam

setup-just:
  #!/bin/bash
  echo 'Backing up current justfile to ~/.justfile-bak ...'
  mv ~/.justfile ~/.justfile-bak
  echo 'Copying over justfile from /etc/justfile ...'
  cp /etc/justfile ~/.justfile

nix-me-up:
  #!/bin/bash
  echo 'Setting phasers to kill. Installing nix.'
  /usr/bin/ublue-nix-install

update:
  #!/usr/bin/env bash
  echo "Staging system update..."
  rpm-ostree update

  echo "Updating Flatpaks..."
  flatpak update -y

  echo "Updating Distroboxes..."
  distrobox upgrade -a
