[misc]
only = ["brew_cask", "brew_formula", "flatpak", "system"]
ignore_failures = ["brew_cask", "brew_formula", "flatpak"]
skip_notify = true
assume_yes = true
no_retry = false
no_self_update = true

[flatpak]
use_sudo = false

[linux]
rpm_ostree = true
