name: Zeliblue Deck
on:
  workflow_run:
    workflows: ["Zeliblue Testing"]
    types: [completed]
  workflow_dispatch: # allow manually triggering builds

jobs:
  build_deck:
    name: Zeliblue Deck Testing
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      recipe: gnome/zeliblue-deck.yml
